### ISSUE TITLE
fail to load plugin descriptor from file patcher.jar

### ISSUE THREAD

**Issue by lighttheripper** [serical/patcher#2]
按照readme的描述也没安装成功 ，这是install plugin from disk时的提示的

**Comment by serical** [comment]
你是什么版本的idea，2018.2.3亲测可以

**Comment by lighttheripper** [comment]
> 
> 
> 你是什么版本的idea，2018.2.3亲测可以

我也是 2018.2.3 呀 我放在这里了 D:\IDE\xxxxxidea\.IntelliJIdea\config\plugins\patcher.jar  重启后 右键没有create patcher

**Comment by serical** [comment]
我是从file-settings-plugin-install plugin from disk可以😂

**Comment by lighttheripper** [comment]
我都试了 标题描述的情况就是你说的install plugin from disk啊

**Comment by serical** [comment]
那就不知道了，我用windows和manjaro都可以

**Comment by GuaoGuao** [comment]
我前面都成功了，最后点击ok后提示Create Patcher Error!
idea版本是2017.2.6，是太旧了么

**Comment by serical** [comment]
> 我前面都成功了，最后点击ok后提示Create Patcher Error!
> idea版本是2017.2.6，是太旧了么

这个只针对了JavaWeb项目，导出的时候有个选择是Web path 相当于WebRoot的概念，需要填写正确
